# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

arr = np.random.uniform(low=0, high=20, size=(4, 7))

min_val = np.min(arr)
max_val = np.max(arr)

a = 1.0 / (max_val - min_val)
b = -min_val * a

normalized_arr = a * arr + b
print(normalized_arr)

[[0.2378784  0.87444669 0.01647786 0.29745975 0.         0.95081968
  0.3202982 ]
 [0.1336109  0.08320149 0.69632854 0.90415879 0.53431656 0.81966232
  1.        ]
 [0.51421538 0.17691386 0.96769113 0.81544623 0.9219134  0.23429438
  0.26957772]
 [0.93849515 0.25648751 0.82876472 0.47652702 0.94524055 0.88079031
  0.14073347]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np

matrix = np.random.randint(0, 11, size=(8, 10)) #создаём матрицу размером 8x10

min_sum_index = np.argmin(np.sum(matrix, axis=1)) #с помощью метода построчно ищем минимальную сумму и выводим запоминаем строку и ее индекс

print("Пример матрицы:")
print(matrix)
print("Ответ:")
print("индекс: ", min_sum_index)
print("строка: ", matrix[min_sum_index])

Пример матрицы:
[[10  8  5  0  9  0  7  5  3  5]
 [ 5  7  7 10  0  7  7  7  6 10]
 [ 4  3  6  0  6  5  0  8 10 10]
 [ 9  6  3  3  8  8  4  8 10  9]
 [ 8  7  0 10  3  3 10  2 10  2]
 [ 5  4  1  4  5  4  4  0  4  9]
 [ 8  1  9  6  9  4  5  5  1  0]
 [ 8  4  5  3  3  4  9  0  9  6]]
Ответ:
индекс:  5
строка:  [5 4 1 4 5 4 4 0 4 9]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

euclidean_distance = np.linalg.norm(v1 - v2)

print(euclidean_distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np

A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.solve(A, -np.dot(C, np.linalg.inv(B)))

print(X)


TypeError: 'dtype' is an invalid keyword argument for print()

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
from google.colab import files

uploaded = files.upload()

data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows = 1, dtype=np.int32)

print(data[:5])

Saving minutes_n_ingredients.csv to minutes_n_ingredients (9).csv
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
"""mean_values = np.mean(data[:, 1:], axis = 0)
min_values = np.min(data[:, 1:], axis = 0)
max_values = np.max(data[:, 1:], axis = 0)
median_values = np.median(data[:, 1:], axis = 0)

print(mean_values)
print(min_values)
print(max_values)
print(median_values)"""
arr = data[:, 1:]
min_first = min(data[:,1])
min_second = min(data[:, 2])
max_first = max(data[:,1])
max_second = max(data[:, 2])
median_minutes = np.median(data[:, 1])
median_ingredients = np.median(data[:, 2])
mean_minutes = np.mean(data[:,1])
mean_ingredients = np.mean(data[:, 2])
print("среднее значение: ", mean_minutes, mean_ingredients)
print("минимальное :", [min_first, min_second])
print("максимальное :", [max_first, max_second])
print("медиана ", median_minutes, median_ingredients)

среднее значение:  39.11163 9.05528
минимальное : [1, 1]
максимальное : [65, 39]
медиана  40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
quint = np.array(np.quantile(data[:, 1], 0.75, axis=0), dtype=int)
print(quint)

65


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
count = np.count_nonzero(data[:, 1] == 0)
print(count)
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])
count = np.count_nonzero(data[:, 1] == 0)
print(count)

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
arr = np.unique(data[:, 1:])
print(len(arr))

655


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
ingredient_counts = data[:, 2]

unique_values, value_counts = np.unique(ingredient_counts, return_counts=True)

print("Различные значения количества ингредиентов и их частота встречаемости:")
for value, count in zip(unique_values, value_counts):
    print(f"Количество ингредиентов: {value}, Частота встречаемости: {count}")


Различные значения количества ингредиентов и их частота встречаемости:
Количество ингредиентов: 1, Частота встречаемости: 13
Количество ингредиентов: 2, Частота встречаемости: 926
Количество ингредиентов: 3, Частота встречаемости: 2895
Количество ингредиентов: 4, Частота встречаемости: 5515
Количество ингредиентов: 5, Частота встречаемости: 7913
Количество ингредиентов: 6, Частота встречаемости: 9376
Количество ингредиентов: 7, Частота встречаемости: 10628
Количество ингредиентов: 8, Частота встречаемости: 10951
Количество ингредиентов: 9, Частота встречаемости: 10585
Количество ингредиентов: 10, Частота встречаемости: 9591
Количество ингредиентов: 11, Частота встречаемости: 8297
Количество ингредиентов: 12, Частота встречаемости: 6605
Количество ингредиентов: 13, Частота встречаемости: 4997
Количество ингредиентов: 14, Частота встречаемости: 3663
Количество ингредиентов: 15, Частота встречаемости: 2595
Количество ингредиентов: 16, Частота встречаемости: 1767
Количество ингредиентов: 1

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
filtered_data = data[data[:, 2] <= 5]
print(filtered_data)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
count_recipes = data[:, 2] / data[:, 1]
ans_8 = np.max(data[:, 2] / data[:, 1])
ans_8

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
ans_9 = data[data[:, 1].argsort()][::-1]
answer_9 = np.mean(ans_9[:100, 2])
answer_9

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
print(*random.choices(data, k = 10), sep="\n")

[356320     45     10]
[449087     35     14]
[170440     15     12]
[523246     15      8]
[287105     35      8]
[36548   135     8]
[284947     25     11]
[262945     60     13]
[367853     10      8]
[411147    140      8]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
average_11 = np.mean(data[:,2] < np.mean(data[:, 2]))*100
average_11

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
simple_recipe = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data = np.column_stack((data, simple_recipe))
print(data)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
arr = data[data[:, -1] == 1]
print(len(arr)/len(data))

0.00013


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
recipes = []
for row in data:
    recipes.append(row)

# Определение максимального количества рецептов из каждой группы
short_recipes = 0
standard_recipes = 0
long_recipes = 0

for recipe in recipes:
    duration = int(recipe[1])
    if duration < 10:
        short_recipes += 1
    elif duration < 20:
        standard_recipes += 1
    else:
        long_recipes += 1

# Создание трехмерного массива
array = np.zeros((3, max(short_recipes, standard_recipes, long_recipes), len(recipes[0])))

# Вывод формы полученного массива
print(array.shape)


(3, 79751, 3)
